runtime: nodejs20

handlers:
  - url: /manifest\.json$
    static_files: dist/client/manifest.json
    secure: always
    upload: dist/client/manifest.json
    http_headers:
      X-Frame-Options: deny

  - url: /ssr-manifest\.json$
    static_files: dist/client/ssr-manifest.json
    secure: always
    upload: dist/client/ssr-manifest.json
    http_headers:
      X-Frame-Options: deny

  - url: /assets/(.*\.(gltf|gif|png|svg|ttf|jpeg|jpg|css|css.map|js|jsx|ts|tsx|pdf|scss|ico|json|json.map|txt|xml))$
    static_files: dist/client/assets/\1
    secure: always
    upload: dist/client/assets/(.*)
    http_headers:
      X-Frame-Options: deny

  - url: /reports/(.*\.(gltf|gif|png|svg|ttf|jpeg|jpg|css|css.map|js|jsx|ts|tsx|pdf|scss|ico|json|json.map|txt|xml))$
    static_files: dist/client/reports/\1
    secure: always
    upload: dist/client/reports/(.*)
    http_headers:
      X-Frame-Options: deny

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
