version: 2.1

executors:
  gcp:
    docker:
      - image: alsco77/node-gcp-dockerfile:origin
    resource_class: medium
  node:
    docker:
      - image: circleci/node:15.3.0
    resource_class: medium
jobs:
  build:
    executor: node
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: dependency-cache-v2-{{ checksum "yarn.lock" }}
      - run:
          name: 'Install and build'
          command: |
            yarn install
            yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - project/*
            - project/dist/*
            - project/dist/client/*
            - project/dist/server/*
      - save_cache:
          key: dependency-cache-v2-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  deployStaging:
    executor: gcp
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: 'Deploy'
          command: |
            echo "Deploy to staging target GAE instance with project ID $S_GCP_PROJECT_ID"
            echo $S_GCP_KEY > /tmp/$CI_PIPELINE_ID.json
            gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
            gcloud config set project $S_GCP_PROJECT_ID
            gcloud --quiet app deploy app.yml
  deployProd:
    executor: gcp
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: 'Deploy'
          command: |
            echo "Deploy to prod target GAE instance with project ID $P_GCP_PROJECT_ID"
            echo $P_GCP_KEY > /tmp/$CI_PIPELINE_ID.json
            gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
            gcloud config set project $P_GCP_PROJECT_ID
            gcloud --quiet app deploy app.yml
workflows:
  version: 2.1
  staging:
    jobs:
      - build
      - Approval:
          type: approval
      - deployStaging:
          requires:
            - Approval
            - build
  prod:
    jobs:
      - Approval:
          type: approval
      - build:
          requires:
            - Approval
      - deployProd:
          requires:
            - build
